### ISSUE TITLE
FargateのアイコンをクリックするとCloudFrontのページが表示される

### ISSUE THREAD

**Issue by naofumi-fujii** [nishinoshake/aws-rough#13]
https://aws-rough.cc/ でFargateのアイコンをクリックしてみたらCloudFrontの計算ページが表示されてしまいました。
何回か試してみたところ、表示される計算ページがランダムで変わるようなのでもしかしたらガチャの機能と同じになっちゃってるのかもしれないです
他のサービスのアイコンも試してみましたが、ランダム表示になっちゃってるかもです。

**Comment by nishinoshake** [comment]
@naofumi-fujii 
ご報告いただきありがとうございます！
指摘いただいたとおり、リンクでガチャを回してました。。

修正反映しております！
https://aws-rough.cc
