### ISSUE TITLE
「共有URLを発行」が機能していない？

### ISSUE THREAD

**Issue by daichiiiiiii** [nishinoshake/aws-rough#44]
はじめまして。いつも利用させていただいています。

見積料金を共有しようと思ったのですが、
料金内訳のページで
「共有URLを発行」ボタンを押すと、
いつも下記メッセージが表示されます。

　リンクを作成できませんでした。
　すみませんがもう一度お願いします・・・

コピーされたURLにアクセスすると

　データを復元できませんでした

のメッセージが表示されます。
こちら、正常にURLを発行する手順などありましたらご教示お願いいたします。

**Comment by nishinoshake** [comment]
@daichiiiiiii 
ご報告ありがとうございます！
恥ずかしながら、共有URLを発行しているサーバーの証明書の期限が切れていました...

更新しておりますので、ご確認お願いいたします！
https://aws-rough.cc/detail/?z=efa5388f1a1c8d605e6c

**Comment by daichiiiiiii** [comment]
@nishinoshake 
早速のご対応ありがとうございます！
一人でメンテするの大変ですよね。。。
ご苦労様です！

共有URL、発行できました！ありがとうございます！
